import { chromium } from 'playwright';
const out = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
await p.goto('http://localhost:8800/');
await p.waitForSelector('[data-testid=chart]');
await p.waitForTimeout(3000);
await p.screenshot({ path: `${out}/01-normal.png`, fullPage: true });
await p.click('[data-testid=inject-cooling]');
await p.waitForSelector('[data-testid=event-COOLING_ANOMALY]', { timeout: 60000 });
await p.click('[data-testid=event-COOLING_ANOMALY]');
await p.waitForSelector('[data-testid=approval-form]', { timeout: 90000 });
await p.screenshot({ path: `${out}/02-pending-approval.png`, fullPage: true });
const tools = await p.$$eval('[data-testid=tool-call]', els => els.map(e => e.innerText.split('\n')[0]));
console.log('tools', tools);
await p.click('[data-testid=approve]');
await p.waitForSelector('[data-testid=action-log]', { timeout: 30000 });
await p.waitForTimeout(6000);
await p.screenshot({ path: `${out}/03-verifying.png`, fullPage: true });
await p.waitForSelector('[data-testid=verification]', { timeout: 120000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/04-closed.png`, fullPage: true });
console.log('flow', await p.$eval('[data-testid=flow]', e => e.innerText.replace(/\n/g, ' > ')));
await b.close();
